
import java.awt.Container;
import java.awt.Desktop;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author red2724
 */
public class ShowMaterial extends javax.swing.JFrame {

    /**
     * Creates new form ShowMaterial
     */
    public ShowMaterial(String classCode,String title) {
        this.classCode = classCode;
        this.title = title;
        initComponents();
        init();
    }
    
    void init(){
        c = this.getContentPane();
        c.setLayout(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //setResizable(false);
        setBounds(100,50,1000,600);
        
        try {
            conn = Connector.ConnectDatabase();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        panel1 = new JPanel();
        panel1.setBounds(2,2,990,596);
        panel1.setLayout(null);
        Vector<Vector<String> > data = new Vector<>();
        Vector<String> coloumn = new Vector<>();
        
        //coloumn.add("SI");
        coloumn.add("ID");
        coloumn.add("Name");
        coloumn.add("Link");
        
        String choice = classCode + "_" + title;
        
        try {
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM "+choice);
        
            while(rs.next()){
                Vector<String> temp = new Vector<>();

                for(String s : coloumn){
                    temp.add(rs.getString(s));
                }

                data.add(temp);
            }

            stmt.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(ShowMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel model = new DefaultTableModel(data,coloumn);
        table = new JTable(model);
        //table.setEnabled(false);
      
        table.getColumnModel().getColumn(2).setPreferredWidth(500);
        
        table.addMouseListener(new MouseListener(){
            @Override
            public void mouseClicked(MouseEvent e) {
                int row = table.getSelectedRow();
                int col = table.getSelectedColumn();
               
                URI uri = null;
                
                if(col==2){
                    String link = (String) table.getValueAt(row, col);
                    
                    try {
                        uri = new URI(link);
                    } catch (URISyntaxException ex) {
                        Logger.getLogger(ShowMaterial.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    if (Desktop.isDesktopSupported()){
                        try {
                            Desktop.getDesktop().browse(uri);
                        } catch (IOException ex) {
                            Logger.getLogger(ShowMaterial.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
            
        });
        
        
        scroll = new JScrollPane(table,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scroll.setBounds(5,5,1000,1000);
        
        panel1.add(scroll);
        
        c.add(panel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMaterial("a","a").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private Container c;
    private JPanel panel1;
    private JTable table;
    private JScrollPane scroll;
    
    private String classCode,title;
    
    Connection conn = null;
    Statement stmt = null;
    PreparedStatement pStmt = null;
    ResultSet rs = null;
}
