
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Redowan
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() throws ClassNotFoundException, SQLException {
        conn = Connector.ConnectDatabase();
        initComponents();
        setID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSignUp = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblFName = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        fieldFName = new javax.swing.JTextField();
        fieldLName = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        comboDept = new javax.swing.JComboBox<>();
        lblType = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblSession = new javax.swing.JLabel();
        lblReligion = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblCPassword = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();
        comboSession = new javax.swing.JComboBox<>();
        comboGender = new javax.swing.JComboBox<>();
        comboReligion = new javax.swing.JComboBox<>();
        fieldPassword = new javax.swing.JPasswordField();
        fieldCPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 100));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignUp.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignUp.setText("Sign Up Form");
        lblSignUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 13, 172, -1));

        lblId.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblId.setText("ID");
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 96, 71, -1));

        lblFName.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblFName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFName.setText("First Name");
        getContentPane().add(lblFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 151, -1, -1));

        lblLName.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblLName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLName.setText("Last Name");
        getContentPane().add(lblLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 211, -1, -1));

        lblEmail.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 286, -1, -1));

        lblPhone.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhone.setText("Phone");
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 351, -1, -1));

        lblDepartment.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDepartment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDepartment.setText("Department");
        getContentPane().add(lblDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 425, -1, -1));

        fieldID.setEditable(false);
        fieldID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fieldID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(fieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 96, 186, -1));

        fieldFName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fieldFName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(fieldFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 151, 186, -1));

        fieldLName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fieldLName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(fieldLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 211, 186, -1));

        fieldEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fieldEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 286, 186, -1));

        fieldPhone.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fieldPhone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 351, 186, -1));

        comboDept.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        comboDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "SWE", "EEE" }));
        comboDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeptActionPerformed(evt);
            }
        });
        getContentPane().add(comboDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 424, 186, -1));

        lblType.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblType.setText("Type");
        getContentPane().add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 96, 116, -1));

        lblGender.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGender.setText("Gender");
        getContentPane().add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 211, 115, -1));

        lblSession.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblSession.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSession.setText("Session");
        getContentPane().add(lblSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 151, -1, -1));

        lblReligion.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblReligion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReligion.setText("Religion");
        getContentPane().add(lblReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 286, -1, -1));

        lblPassword.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 351, -1, -1));

        lblCPassword.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblCPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCPassword.setText("Confirm Password");
        getContentPane().add(lblCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 425, -1, -1));

        comboType.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher", "Student" }));
        comboType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 96, 186, -1));

        comboSession.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        comboSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017-18", "2018-19", "2019-20", "2020-21" }));
        comboSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSessionActionPerformed(evt);
            }
        });
        getContentPane().add(comboSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 151, 186, -1));

        comboGender.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        comboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGenderActionPerformed(evt);
            }
        });
        getContentPane().add(comboGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 211, 186, -1));

        comboReligion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        comboReligion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Muslim", "Hindu", "Christian", "Buddhist", "Others" }));
        comboReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboReligionActionPerformed(evt);
            }
        });
        getContentPane().add(comboReligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 286, 186, -1));

        fieldPassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fieldPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 351, 186, -1));

        fieldCPassword.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fieldCPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(fieldCPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 425, 186, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setMaximumSize(new java.awt.Dimension(105, 31));
        btnBack.setMinimumSize(new java.awt.Dimension(105, 31));
        btnBack.setPreferredSize(new java.awt.Dimension(105, 31));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 517, 101, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setMaximumSize(new java.awt.Dimension(105, 31));
        btnClear.setMinimumSize(new java.awt.Dimension(105, 31));
        btnClear.setPreferredSize(new java.awt.Dimension(105, 31));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 517, 101, -1));

        btnConfirm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 517, 110, -1));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profileandsignup.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblImage)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setID() throws ClassNotFoundException, SQLException {
        id = ID.getID();
        fieldID.setText(Integer.toString(id));
    }

    private void comboDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeptActionPerformed
        // TODO add your handling code here:
        choiceDept = comboDept.getSelectedItem().toString();
    }//GEN-LAST:event_comboDeptActionPerformed

    private void comboTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTypeActionPerformed
        // TODO add your handling code here:
        choiceType = comboType.getSelectedItem().toString();
    }//GEN-LAST:event_comboTypeActionPerformed

    private void comboSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSessionActionPerformed
        // TODO add your handling code here:
        choiceSession = comboSession.getSelectedItem().toString();
    }//GEN-LAST:event_comboSessionActionPerformed

    private void comboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGenderActionPerformed
        // TODO add your handling code here:
        choiceGender = comboGender.getSelectedItem().toString();
    }//GEN-LAST:event_comboGenderActionPerformed

    private void comboReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboReligionActionPerformed
        // TODO add your handling code here:
        choiceReligion = comboReligion.getSelectedItem().toString();
    }//GEN-LAST:event_comboReligionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            LoginPage login = new LoginPage();
            login.setLocationRelativeTo(null);
            login.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        fieldFName.setText("");
        fieldLName.setText("");
        fieldEmail.setText("");
        fieldPhone.setText("");
        fieldPassword.setText("");
        fieldCPassword.setText("");
        choiceType = "";
        choiceGender = "";
        choiceReligion = "";
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        fName = fieldFName.getText();
        lName = fieldLName.getText();
        password = Hash.getHash(fieldPassword.getText());
        confirmPassword = Hash.getHash(fieldCPassword.getText());
        email = fieldEmail.getText();
        phone = fieldPhone.getText();

        if (!(password.equals(confirmPassword))) {
            JDialog dialog = new JDialog();
            dialog.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(dialog, "Password and Confirm Password Must be Same", null, JOptionPane.PLAIN_MESSAGE);
        } else {
            try {

                
                    stmt = conn.prepareStatement("INSERT INTO " + choiceType + " VALUES(?,?,?,?,?,?,?,?,?,?)");
                    stmt.setInt(1, id);
                    stmt.setString(2, fName);
                    stmt.setString(3, lName);
                    stmt.setString(4, choiceDept);
                    stmt.setString(5, choiceSession);
                    stmt.setString(6, password);
                    stmt.setString(7, email);
                    stmt.setString(8, phone);
                    stmt.setString(9, choiceGender);
                    stmt.setString(10, choiceReligion);
                    stmt.execute();
                    stmt.close();
                

                String tableName = "_" + fieldID.getText();
                String op = "CREATE TABLE " + tableName + " ("
                        + " Course_Code VARCHAR(100) NOT NULL, "
                        + " Course_Name VARCHAR(100) NOT NULL, "
                        + " Session VARCHAR(100) NOT NULL, "
                        + " Section VARCHAR(100) NOT NULL, "
                        + " PRIMARY KEY (`Course_Code`))";

                stmt = conn.prepareStatement(op);
                stmt.execute();
                stmt.close();

                JDialog dialog = new JDialog();
                dialog.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(dialog, "Congratulations!!! Account Created Successfully", null, JOptionPane.PLAIN_MESSAGE);

                setVisible(false);
                LoginPage login = new LoginPage();
                login.setLocationRelativeTo(null);
                login.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SignUp().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> comboDept;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboReligion;
    private javax.swing.JComboBox<String> comboSession;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JPasswordField fieldCPassword;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldFName;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldLName;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPassword;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblReligion;
    private javax.swing.JLabel lblSession;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables

    private String choiceType, choiceGender, choiceReligion, choiceDept, choiceSession;
    private int id;
    private String fName, lName, password, email, phone, confirmPassword;

    Connection conn = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;
}
